### ISSUE TITLE
Add Space screw Graph Editor

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#104]
I think this is going to be a tough one. I think we may need to capture what handle types the graph editor is using. It feels like the tangent handles are getting left behind.

The tangent type on the graph editor curve handles might be getting to set to free? I will look at it again tomorrow morning.

pay attention to the curves when the spacing is added. The animation starts out smooth and then after the spacing the animation to starts to look like it stuttering.

https://user-images.githubusercontent.com/16330340/217274689-7f632ee6-b9a0-4f6a-9a22-647a1060d8e5.mp4

**Comment by SuddenDevelopment** [comment]
ready to try
