### ISSUE TITLE
Pin  frames to moved into a collection.

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#106]
When frames are pin from multiple objects have them put into a collections folder at the root level of the scene collection to be easily found. 

Color the folder red
![image](https://user-images.githubusercontent.com/16330340/217705748-1a43fc47-5b18-44a5-85f0-1d4f9c6a9454.png)

**Comment by SuddenDevelopment** [comment]
this was done, I think it;'s a duplicate issue
