### ISSUE TITLE
Pin Frame is not working on Chalk Man Rig

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#107]
Pin Frame is not working on Chalk Man Rig.  I think this is because of parenting.

https://user-images.githubusercontent.com/16330340/217706068-a46a0126-d691-4cb9-af6a-38fb94a908a9.mp4

**Comment by SuddenDevelopment** [comment]
fixed issue with radius and tilt keys, should help others...

doesnt help the location reset.

**Comment by SuddenDevelopment** [comment]
I got everything working it seems besides clearing or applying constraints without side effects. everything I do moves it

**Comment by SuddenDevelopment** [comment]
fixed, by copying all contraint targets and retargeting to copies

**Comment by adamearle** [comment]
Ok I am Chalking this one up as working.

For some reason, the head turn animation doesn't work.  but for every other animation that I have done from scratch, it seems to work.
