### ISSUE TITLE
Duplicate Key not Colouring both keys Purple

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#116]
### 2 Problems 
Duplicate Key isn't coloring both keys Purple when a keyset is within the keyframes zone. 
Keyframe also needs to be set at the playhead. 

https://user-images.githubusercontent.com/16330340/218656800-746ef370-9d8d-4924-9392-ebfd8f0f5133.mp4

**Comment by SuddenDevelopment** [comment]
please recheck
