### ISSUE TITLE
PinFrame Clearing keyframes needs to work even when objects are not selected 

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#118]
1. Pin frames need be cleared even when objects are not cleared.
2. The collection folder needs be at the root level of the scene for all objects
3. Ojects to be housed in there own collection for user control ie. 

Collection folder should remain closed
![image](https://user-images.githubusercontent.com/16330340/218664395-3e214e66-7f2a-4adf-8492-9d5b9aef0f32.png)

**Comment by SuddenDevelopment** [comment]
I thought it was already being created at root level

**Comment by SuddenDevelopment** [comment]
ready to test, should be what you asked for or close
