### ISSUE TITLE
Adding AnimAll Button to the viewport panel

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#123]
**AnimAll Notes:** [https://github.com/SuddenDevelopment/animall-autokey/wiki/Notes-on-the-AnimAll-Autokey-Addon](https://github.com/SuddenDevelopment/animall-autokey/wiki/Notes-on-the-AnimAll-Autokey-Addon)

___
### How to do this? I will do up sketches.
Creating the stop motion version of AnimAll keying behavior to install 2 keys to the view panel when the addon is enabled.

1. Insert key _(user-defined)._
2. Delete key _(user-defined)._

StopMotion keys are to be color coded as a default behavior using the Key Type Jitter making the keys green based on the StopMoTion settings.

Works with autokey.

**Button Placement.**
![image](https://user-images.githubusercontent.com/16330340/219055380-cf816bb6-35af-42e3-89a1-43aa32382b66.png)

____
**User-Defined settings**
99% of the time the user is defining the settings for a particular reason. Set & forget mentality.

**Mesh:**
**Points:** Location, Bevel, Vertex Groups
**Edge:** Bevel, Crease,
**Face:** Material index
**Others:** Attributes

**Curves & Surface:** _(these have the same settings)_
**Points:** Location, Radius, Tilt
**Splines:** Material Index
**Others:** Shape Keys

___
**Bug Fixes;**
1. Sometimes verts aren't placed in their correct dropdown and are exposed out in the wild.
1. Dropdown menu in the dope sheet opens automatically
1. keyframe changes aren't committed unless something is moved on screen

**Comment by SuddenDevelopment** [comment]
added.
