### ISSUE TITLE
Keying  AnimAll StopMotion

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#125]
The default add key needs to be keyed the same time as the animal key gets keyed.

the 2 are in conflict with each other.

**Comment by adamearle** [comment]
testing Required

**Comment by SuddenDevelopment** [comment]
my basic tests work... you are saying if someone clicks on animall it needs to auto do a stop motion key?

what if they do it from the animall addon? Do we need to include it and override the animall n panel function?
