### ISSUE TITLE
Cut Copy Paste

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#14]
### Copy Cut & Paste: 
> ### Keys 
> Animator always have one hand on screen this is too prevent menu diving and promote working quickly 
_(Already Available)_ 
> Buttons live in: Dopesheet & Graph Editor.

############
The following 2 perhaps could perhaps be rolled into one?
Copying objects could just **select all** in edit mode and then combine the data across?

> ### Data
>  Selected data, Verts meshes edges is copied / cut  & pasted into the current animation data set.
> _(Not available)_
> Buttons live in: Viewport.
> 
> ### Objects 
> Selected objects are copied / cut  & pasted into the currently active animation data set. Works in object and edit mode.
> _(Not available)_
> Buttons live in: Viewport.

**Comment by SuddenDevelopment** [comment]
isn't this the same as inserting the selected into active at current frame?

**Comment by SuddenDevelopment** [comment]
https://docs.blender.org/api/current/bpy.ops.view3d.html#bpy.ops.view3d.copybuffer

https://docs.blender.org/api/current/bpy.ops.view3d.html#bpy.ops.view3d.pastebuffer
