### ISSUE TITLE
UI Controls

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#17]
**Controls:**
Controls can be enabled and disabled in different parts of the interface.
> 1. N-panel.
> 2. Floating menu Viewport, Dopesheet & Graph Editor.
>     Left, Right, Top, Bottom.
> 3. Pie Menu.
> 

Mock ups need to be done?

**Comment by SuddenDevelopment** [comment]
what do you think of the "t" menu?
