### ISSUE TITLE
Button Description

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#18]
### Onion Skin
![Onion skin](https://user-images.githubusercontent.com/16330340/210032111-59b4b464-a281-49f7-922d-95342204aa7e.png)
**Onion Skin**
Onion Skin enables the ability to see pre and post-frames of the currently active frame.

![Pin Frame](https://user-images.githubusercontent.com/16330340/213637223-5090a8aa-d5e4-4542-ba72-7d54f7f39b98.png)
**Pin Frame:** Sets the selected object/s to be used as a reference object for working in and out of poses.

**Button behaviors:**
1. **Click:** Pins the current selection
2. **Ctrl +Click:** Removes all pin frames

___
### Stop Motion keys
![Key Clear](https://user-images.githubusercontent.com/16330340/210905929-21dbf702-b9e8-494b-8b30-3049a8b26a78.png)
**Clear keyframes:** Keyframe is not removed _(not deleted)_.
Clears the id data from the currently selected StopMotion object. 
If the geometry is selected in edit mode only the current selection is removed from the StopMotion object.

___
![Key Insert](https://user-images.githubusercontent.com/16330340/210031403-8b54bd2e-03a6-45d9-bfc8-25fa81e94e68.png)
**Add Keyframe:** Adds and inserts a single keyframe with a unique **StopMotion Object id** 

**Button behaviors:**
1. **Click:** Insert add/ insert a keyframe to the **Right** of the timeline indicators playhead.
2. **Ctrl +Click:** Insert add/ insert a keyframe to the **Left** of the timeline indicators playhead.

![Key Remove](https://user-images.githubusercontent.com/16330340/210031430-486a3bac-f9b6-48a8-b6f2-b2a118b619bc.png)
**Remove keyframe:** Removes the current keyframe and pulls keyframes into the deleted keyframe position. 
Right & Left of the timeline indicators playhead. This is like deleting a keyframe.

**Button behaviors:**
1. **Click:** Remove/Deletes insert a keyframe to the **Right** of the timeline indicators playhead.
2. **Ctrl +Click:** Remove/Deletes a keyframe to the **Left** of the timeline indicators playhead.

![Key Insert Blank](https://user-images.githubusercontent.com/16330340/210031470-650c19e1-c6f5-4c40-9053-340ad2893e07.png)
**Insert Blank Keyframe:** Inserts a single blank keyframe to the right of the timeline indicators playhead.

**Button behaviors:**
1. **Click:** insert a blank keyframe to the **Right** of the timeline indicators playhead.
2. **Ctrl +Click:** insert a blank keyframe to the **Left** of the timeline indicators playhead.

![Key Insert Many Blank](https://user-images.githubusercontent.com/16330340/213633772-a9aab5bb-497b-4b84-a4ef-f507ec06f00c.png)
**Insert Multiple Blank keyframes:** Numerical value set how many blank keyframes will be added to the timeline indicators playhead.

**Button behaviors:**
1. **Click:** insert multple blank keyframe to the **Right** of the timeline indicators playhead.
2. **Ctrl +Click:** insert multple blank keyframe to the **Left** of the timeline indicators playhead.

___
### Duplicate
![Key Duplicate](https://user-images.githubusercontent.com/16330340/210031655-0b0aae9c-a30a-41a5-9978-39a636c6fb97.png)
**Duplicate Keyframe:** Duplicates the current keyframe to the right of the current active keyframe/s.

![Duplicate Object   Keys](https://user-images.githubusercontent.com/16330340/210033706-0a826d6c-09c2-46f0-bda8-8e587707db50.png)
**Duplicate Object With Keys:** Duplicates the object/s and the current keyframes with a unique id.

![Duplicate Object With Blank Keys](https://user-images.githubusercontent.com/16330340/210032382-907b62ed-e916-4f7f-ad97-170c1dc4b88e.png)
**Duplicate Object With Blank Keys:** Duplicates the object/s with blank keyframes.

___
### Frame Spacing
![Space Add](https://user-images.githubusercontent.com/16330340/211740106-e81c9abe-23fb-4c2d-8a20-9d7ee2ac689b.png)
**Frame Spacer: _Add_**
Adds a single extra space between selected keyframes. 

![Space Remove](https://user-images.githubusercontent.com/16330340/211740142-7292e286-2f95-4cda-add9-c6212e93fd02.png)
**Frame Spacer: _Subtract_**
Subtracts a single space between selected keyframes. Accumulative behavior till there are no more spaces between keyframes. Does not delete keys.

**Frame Spacer: _Count_:** Sets the number value limit between keyframes.

![Space None](https://user-images.githubusercontent.com/16330340/211740174-d86c8519-2cb0-4a46-a2c8-69b7a20739cd.png)
**Frame Spacer: _None_:** Applies the current number of spaces between keyframes.

![Space Set](https://user-images.githubusercontent.com/16330340/211750431-4984aac7-e785-4151-9cc7-2410d6443352.png)
**Frame Spacer: _Set_:**Applies the current number of spaces between keyframes.

___
### Object Frames
![Seperate selection](https://user-images.githubusercontent.com/16330340/210033841-626d941a-9700-4516-aed0-7146d3e659a6.png)
**Sperate Selection:** Separates and converts the currently active selection in edit mode to a new object.

**Button behaviors:**
1. **Click:** Creates a Copy from the object or selection.
2. **Ctrl +Click:** Cuts the current object or selection to a new object.

![Combine With Active Object](https://user-images.githubusercontent.com/16330340/210033908-60f6097d-346d-493e-9c49-3ee9c17dbef4.png)
**Combine With Active Object:** Combines the selected object with the active merging keyframe data

**Button behaviors:**
1. **Click:** Combines with the active objects selections keyframe.
2. **Ctrl + Click:**  Create new keyframes from the active object.

___
### Asset Library
![Add To Asset Library](https://user-images.githubusercontent.com/16330340/210031151-1926d374-ea34-4653-8ffa-e29e2d318332.png) 
**Asset Library:** Create assets out of what is selected. **Object & Edit mode** and **Keyframe data** is supported.

**Comment by SuddenDevelopment** [comment]
this helps, thanks

**Comment by SuddenDevelopment** [comment]
deferring till after launch:

1.     insert multiple blank keyframes
2.     onion skin
3.     frame space count slider (will be in n menu)

**Comment by adamearle** [comment]
**insert multiple blank keyframes**
Perhaps this can be done similar as setting key frame spaces?

**Comment by adamearle** [comment]
I have removed unique keyframe and added clear keyframe

**Comment by adamearle** [comment]
Duplicating the object with the same keyframes and no geometry data for any of the keyframes I think this is what you mean for your notes

**Comment by adamearle** [comment]
Let's nail down these button descriptions so that there better.

**Comment by adamearle** [comment]
Well done on doing that by the way as well.

**Comment by adamearle** [comment]
We need to work on some of these description names. 

I prefer well-described content. The larger the tooltip the better. 
If we could get animated gifs in the tooltips I would do that.

I prefer to not leave the user guessing and have the tooltips well formatted.

**Comment by adamearle** [comment]
Descriptions have been updated

**Comment by SuddenDevelopment** [comment]
applied, going to remove the high priority tag from it now but we should keep it for the unimplemented buttons
