### ISSUE TITLE
frame spacing subtraction is removing keys

### ISSUE THREAD

**Issue by SuddenDevelopment** [SuddenDevelopment/StopMotion#21]

**Comment by SuddenDevelopment** [comment]
fixed, removing frame space will only remove spaces available to move, shouldn't stack keys which makes them look lost.

sending back to you to test

**Comment by adamearle** [comment]
Well done.  Just tested this and its not deleting keyframes. 

Small fix here needed when pressing the delete key, it doesn't remove the space completely.

https://user-images.githubusercontent.com/16330340/210896228-2d4a941d-fc28-4824-a9bc-cbd0fb79c1e8.mp4
