### ISSUE TITLE
Blank Keyframe must carry settings 

### ISSUE THREAD

**Issue by SuddenDevelopment** [SuddenDevelopment/StopMotion#22]
blank keyframes need every but geo to be set, creating a new data block doesnt copy enough from the original object

**Comment by adamearle** [comment]
The other issue is that the setting are not be carried across.
https://user-images.githubusercontent.com/16330340/210660468-278828bf-d6e7-4783-b8cb-75b19243e286.mp4

**Comment by SuddenDevelopment** [comment]
fixed. please test
