### ISSUE TITLE
Scrubbing in edit mode ends in object mode

### ISSUE THREAD

**Issue by SuddenDevelopment** [SuddenDevelopment/StopMotion#23]
if scrubbing in edit mode need to make sure it stays in edit mode

**Comment by adamearle** [comment]
Scrubbing the viewport keeps it in edit mode.
If the user scrubs the timeline without the addon the will jump from edit to object mode.


[viewport_timeline_scrub-main.zip](https://github.com/SuddenDevelopment/StopMotion/files/10348036/viewport_timeline_scrub-main.zip)

**Comment by SuddenDevelopment** [comment]
couldn't duplicate ?

**Comment by SuddenDevelopment** [comment]
sending back to you to figure out way to reproduce, if it's too hard to consistently reproduce maybe it lowers in priority

**Comment by adamearle** [comment]
If scenes are created in a previous version of Blender it can cause the scrubbing of the timeline to jump out of edit mode into object mode.

### Artist Fix:
Copy your asset into a new scene for the proper behavior to take place.
