### ISSUE TITLE
Cut Copy Paste

### ISSUE THREAD

**Issue by SuddenDevelopment** [SuddenDevelopment/StopMotion#24]
Separate selection does work the way it's intended. 
Keyframes need to be selected in order for the operation to work correctly.

The Current Method needs are really great for separating out whole objects from the keyframe the 

This design doesn't seem to be intuitive enough _(Apologies)_. The user will probably just make the selection in the viewport without looking at what keyframes are selected on the current frame.

If no keyframes are selected and the separate selected operation is activated, the object will become deselected and the keyframes will give the appearance as if they have been deleted.

I can't help but think a simple Cut Copy & Past solution is something that everyone is really familiar with reduce the button count.

Separate selection, merge, and combine,  are available it just seems to take up too much head space when animating.
I should have thought of this sooner

**Github**
https://github.com/dairin0d/blender-2.8-scripts/blob/master/docs/cut_copy_paste/cut_copy_paste.md

**Video**
https://www.youtube.com/watch?v=yaZBOZLbOa0&ab_channel=StevenScott

Development was never finished:
https://developer.blender.org/T31214

Lets talk about this

**Comment by SuddenDevelopment** [comment]
I got the separate objects function working as designed to COPY them out instead of CUT them out

**Comment by SuddenDevelopment** [comment]
https://moth3r.gumroad.com/l/paste

**Comment by adamearle** [comment]
**Cut Copy Paste** works in 3 modes: 


1. Object mode, 
2. Edit mode 
3. Keyframes
4. All of the above from scene to scene

When the cursor is in the viewport it **Cut Copy Paste** the operation works in **Object and Edit mode**
When the cursor is in one of Blender's many timelines it works with keyframes.

___
### Object mode:
Copy Paste already works 
Cut Paste Doesn't work
___
### Edit mode:
Cut or Copy Paste doesn't work
___
### Keyframes:
Already works
Scene to scene doesn't work
