### ISSUE TITLE
Mash keys

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#28]
### **Mashing capability:** 
This means we can remove a button, which simplifies and keeps operations fluid.
Keys are added to the right when there's already an existing keyframe.

___
### **Add keys:** 
Every new key that is added is unique by default. Add should insert keyframes Right of the timeline indicator/ Play head. The play head should move to the new position of the newly inserted keyframe. If there is already a keyframe in the position where the new keyframe is to be added, the other keyframes will move to the right of the timeline to create space for the new keyframe to be inserted.
___
### **Delete key:**  
Deletes the current key and pulls keyframes left.
___
### **Blank keys:**  
Inserts a keyframe to the right of the timeline indicator/ Play head. The play head should move to the new position of the newly inserted blank keyframe. If there is already a keyframe in the position where the new keyframe is to be added the other keyframes will move to the right of the timeline to create space for the new keyframe to be inserted.
___
### **Duplicate key:**  
Pushes keyframes Right of the timeline indicator/ Play head.  Keyframes can also be tagged as hold keys
https://user-images.githubusercontent.com/16330340/210903630-97cb0af0-01d3-44e3-802c-b060f86c12c0.mp4

**Comment by SuddenDevelopment** [comment]
Add Key=>Duplicate Key: insert, move playhead 1 frame, insert key

Blank key behaves same as duplicate keyframe

**Comment by SuddenDevelopment** [comment]
I had the remove keys set up to remove any selected, but that;s not comaptible with this workflow so removing that

**Comment by adamearle** [comment]
The timeline cursor player needs to move forward one frame when the duplicate button is pressed.
https://user-images.githubusercontent.com/16330340/211947360-847b655c-7897-40fb-9397-6703f9033777.mp4

**Comment by adamearle** [comment]
if the initial starting stop-motion key isn't set.
      then one keyframe is created.
      if the initial starting keyframe is set use the current behavior.

https://user-images.githubusercontent.com/16330340/211948197-5eb71ad8-e4b8-4917-87ed-b66f62e4114f.mp4

**Comment by adamearle** [comment]
Best to leave the keys unselected
