### ISSUE TITLE
Duplicate keys to be colour coded 

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#29]
A duplicate key button is clicked the key types are to be changed to hold keys.

This helps the user to know which keys can be tweened

![blender_8kmxTwtCI5](https://user-images.githubusercontent.com/16330340/212245218-487818b9-b2db-4404-8218-c2b64f97a9dc.png)

**Comment by SuddenDevelopment** [comment]
done, ready to test

**Comment by adamearle** [comment]
When a duplicate key is created:

The current key should change to the **hold keys** type as well. this allows the user to know which two keys can be in between.

Hand Animators always need to set 2 keys to create the appearance of movement. 2 keys need to be purple.

**Comment by adamearle** [comment]
Please see the added image above
