### ISSUE TITLE
Scrubbing the timeline doesn't work in edit mode

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#3]
Scrubbing the timeline when in edit mode doesn't update the viewport. This is a much need functionality for animators as they are moving very quickly across the timeline and drawing.

It is very similar to traditional animation except rolling paper tradigital animators are rolling (scrubbing) keys in the timeline.

Here is a link to understand the speed that animators are working. This also demonstrates their thought process while working as well:

[https://www.youtube.com/watch?v=sEVpPYD306k&ab_channel=TheArtofAaronBlaise](https://www.youtube.com/watch?v=sEVpPYD306k&ab_channel=TheArtofAaronBlaise)

https://user-images.githubusercontent.com/16330340/202595241-b14862a7-d233-4872-baeb-b7802b2f7184.mp4

**Comment by adamearle** [comment]
Scrubbing the timeline when in edit mode doesn't update the viewport

**Comment by SuddenDevelopment** [comment]
at the moment, this is intentional because edit mode and object mode are pretty separate in terms of behavior. I'll remove the restriction and see what happens. This could be a tough one to resolve.

**Comment by SuddenDevelopment** [comment]
It seems I can only swap the geo data and have it show up reliably by swapping in and out of object mode so that the edit mode copy refreshes. I do this automatically now if in edit mode.

**Comment by adamearle** [comment]
> 

Well done boss maaaaaaan
