### ISSUE TITLE
Changed the default Keyframe types colours

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#30]
Changes the default color types when the addon is installed.
![image](https://user-images.githubusercontent.com/16330340/211766136-ad5d7419-27b9-438c-8ed4-8d76dda2e607.png)

Keyframe:  FFBE33
keyframe Selected:  FF0000
Extreme Keyframe:  F28080
Extreme keyframe Selected:  FF0000
Breakdown Keyframe:  54BFED
Breakdown Keyframe Selected:  FF0000
Jitter Keyframe:  61C042
Jitter keyframe Selected:  FF0000
Moving Hold Keyframe:  A200FF
Moving Hold keyframe Selected:  FF0000

**Comment by SuddenDevelopment** [comment]
done, good to test
