### ISSUE TITLE
Add Clear keyframe behavior

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#36]
Time to introduce the Clear frame button in front of the add keyframe button. Make this button its own island _(all rounded corners similar to the create asset button)_ 
![Key Clear](https://user-images.githubusercontent.com/16330340/211955422-88fb464a-02b9-4165-a064-9c87c6f134c3.png)

![image](https://user-images.githubusercontent.com/16330340/211956271-b51dc5f9-e570-4d97-824d-9f59cd0ddef6.png)

**Comment by SuddenDevelopment** [comment]
clear geometry on current frame
stay in edit mode.
