### ISSUE TITLE
Add Insert Stop Motion Keyframes

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#4]
Sometimes when inserting new stop-motion keyframes they flip around on the timeline when exiting edit mode into object mode

**Comment by SuddenDevelopment** [comment]
I'm sure I can handle this one. looking at it

**Comment by SuddenDevelopment** [comment]
took hours to figure out this was NOT a programming mistake.
When you go to frame 6 you are editing the mesh from frame 5, before you ever do an insert. Then when you do an insert the mesh from frame 5 was edited, kept that way and frame 6 is then keyframed as a stop motion snapshot.
I will need to add functionality to prevent this or automate away this unintended result.

**Comment by SuddenDevelopment** [comment]
the manual workaround would be to key a frame before editing anything then key it again after this will make sure the old one is preserved

**Comment by adamearle** [comment]
> the manual workaround would be to key a frame before editing anything then key it again after this will make sure the old one is preserved

This way is bound to cause problems with animators working.

**Comment by adamearle** [comment]
> One possible workaround is to create 2 keyframes on insert.
> 
> 1 = the intended keyframe 2 = a copy in the next frame that can be modified, preventing this issue
> 
> I can;t think of any side effects of this approach yet.

I would go with whatever seems easiest at the moment. To me, copying the keyframe sounds like the easiest. 

That said I remember using Grease Pencil years ago and it was acting up in Blender. This was because some of the animators were working to fast and the python scripts couldn't keep up. This may be something to keep on the radar.

**Comment by SuddenDevelopment** [comment]
if 
enter edit mode:
1,2,3,4, object mode, edit mode, 5,6,7,8
then
1,2,3, -8- ,5,6,7,8

**Comment by SuddenDevelopment** [comment]
the previous mesh data is being overwritted with the final update of the curve / object.

solution may be to keep a temp object in place, never simply point to the old object, this way the previous frame set is not overwritten.

**Comment by SuddenDevelopment** [comment]
allowing it  to copy() the data blocks on swapData instead of referencing them fixes this issue completely...
however, every copy becomes a new object/mesh, which multiplies quickly. after resolving that we are good.

**Comment by SuddenDevelopment** [comment]
fixed, tested, acknowledged, closing
