### ISSUE TITLE
Shipping & enabling addons with stop motion

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#42]
External add-ons to be shipped with our addon that can be enabled (user choice). This should lower the workload for maintenance and keep things more flexible. There is no point in rewriting code that is already freely available. We can demonstrate support I think.

1. Cut Copy Paste:  https://github.com/dairin0d/cut-copy-paste.
2. Viewport Scrubbing: https://github.com/Pullusb/viewport_timeline_scrub.
3. Viewport Rotation: This feature ships with blender **Grease Pencil tools**. The idea here would be to extract just the rotate canvas setting.
4. Lock the viewport: We can customize this one  by creating an icon that sits in the top right-hand corner of the **Tool Setting** 
header.

**Code:** https://gist.github.com/Fweeb/bb61c15139bff338cb17
**Youtube:** https://www.youtube.com/watch?v=1IYOksoqf6Y&ab_channel=StevenScott 

Where to put the lock button:
![image](https://user-images.githubusercontent.com/16330340/212224589-75e0ef68-0e37-4805-bcbf-c16691981b49.png)

**Comment by SuddenDevelopment** [comment]
recommending and supporting are good. I DO NOT think we should ship them unless we get permission from them. Even if they are making for free we are not and we are setting ourselves up for bad will if we ship their stuff as included. 

This is going outside what I think should get the high priority = launch tag.
