### ISSUE TITLE
Clear Keyframe doesn't commit change

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#43]
clearing a keyframe doesn't commit the change.

https://user-images.githubusercontent.com/16330340/212243315-dc0f1367-201f-4dde-b171-7c6a6d523ec3.mp4

**Comment by SuddenDevelopment** [comment]
I didnt think it was mean to..

it clears the data so you can quickly put something else there right? I can have it update the obj data for the frame

**Comment by SuddenDevelopment** [comment]
done, test it out
