### ISSUE TITLE
Button Replace

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#46]
Stroke widths weren't consistent with the other buttons
![Space Add Half Button](https://user-images.githubusercontent.com/16330340/212251421-91da6687-efb2-401f-b76f-64629cd32b86.png)
![Space Non Half Button](https://user-images.githubusercontent.com/16330340/212251424-c66896c0-5247-48f3-97f1-20ae10f5fc56.png)
![Space Remove Half Button](https://user-images.githubusercontent.com/16330340/212251425-5d2281f4-a1cc-4949-9d7a-5b9502c900e4.png)

___
This is a replacement not sure if we should use it or not
![Space Set Half Button](https://user-images.githubusercontent.com/16330340/212251996-cc702fed-de4b-4429-bb75-139cdba6e6b1.png)

**Comment by SuddenDevelopment** [comment]
done
