### ISSUE TITLE
Blank Keyframe needs to move right on creation.

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#48]

**Comment by SuddenDevelopment** [comment]
blank keyframe is created to the right, need to move position with it.

**Comment by SuddenDevelopment** [comment]
this also now looks to see if next frame is blank, if blank it puts the blank key there, if populated it nudges all frame right first

**Comment by adamearle** [comment]
Also needs the same logic as Add Key.

If no keyframe inserts keyframe at current location
If there is a keyframe, move the Timeline indicator playhead to the right of the current position and insert keyframe.

**Comment by SuddenDevelopment** [comment]
done, ready to test

**Comment by adamearle** [comment]
**Right** 
1. No Key on current frame =  Set key. 
2. Key on the current frame = Move playhead right and set key.
3. Key on the current frame and the right of the current frame = Nudge keys and set key.

**Left**
Ctrl key held down on click = Left instead of right

**Comment by SuddenDevelopment** [comment]
left click stuff goes in separate ticket
