### ISSUE TITLE
Duplicate with out Keyframes

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#53]
At the moment if no keyframes are selected nothing happens.

If no keyframes are selected it only works on the current keyframe.
If multiple keyframes are selected it works on all of them.

https://user-images.githubusercontent.com/16330340/212581312-2cd91dbe-1aff-491d-afbe-fd84c3c539d1.mp4

**Comment by SuddenDevelopment** [comment]
should grab previous frame

**Comment by SuddenDevelopment** [comment]
I need help understanding if I'm applying this to the correct operation, the logic is simple just have to make sure it's in the right place
