### ISSUE TITLE
update frame objects on edit

### ISSUE THREAD

**Issue by SuddenDevelopment** [SuddenDevelopment/StopMotion#56]
```
IF stopMotion Object
    Edit mode
        Something is edited:
            propagate change back to frame object from to object
            before swapping object

            determine if there's and update to save unnecessary data BS
            ```

**Comment by SuddenDevelopment** [comment]
ready to test!

**Comment by adamearle** [comment]
You won't believe this it's working on meshes and not curves.
Can you test on curves?

**Comment by adamearle** [comment]
We are going to have to work through this one together. I have been turning everything off to get it working. i still can't get it to work.

Kinda lost for ideas as to why
