### ISSUE TITLE
Seperate  combine and merge buttons

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#59]
These button were working in the previous version

**Comment by SuddenDevelopment** [comment]
appear working

**Comment by adamearle** [comment]
Your matrix idea did the trick I think
![image](https://user-images.githubusercontent.com/16330340/213178454-de992332-971e-4ec8-bc3f-2ccc706aa55c.png)

**Comment by SuddenDevelopment** [comment]
define ctrl actions in the ctrl click issue please

**Comment by adamearle** [comment]
### Separate:
1. Click = Object/Edit mode separate.
2. Ctrl + Click = Edit mode separate selected Copy out.
3. Alt + Click = Edit mode separate selected Cut out.

### Combine:
1. Click = Object Merge with keyframe 
2. Ctrl + Click = Combine object

**Comment by SuddenDevelopment** [comment]
we should reduce to 2 states each:
Separate:
- click = separate COPY selected frames
- ctrl+click =  separate CUT selected frames

I think we should leave combine alone, but we can discuss

**Comment by adamearle** [comment]
Let go with your suggestion Cut- Copy Paste addon can do objects

or 

We could have a cut copy behavior if statements to determine object mode or edit mode?

**Comment by SuddenDevelopment** [comment]
I think we are good to go on this ,now. copied in other tickets too
