### ISSUE TITLE
Clear frame on no selected objects

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#61]
If no object is selected then nothing should happen.

https://user-images.githubusercontent.com/16330340/213037162-91615034-d178-448c-a7b7-8dc4a28ee829.mp4

**Comment by SuddenDevelopment** [comment]
done

**Comment by adamearle** [comment]
There are few things happening here.

1. Sometimes the keyframe will set a keyframe on clear.
2. Sometimes the keyframe will not clear.

https://user-images.githubusercontent.com/16330340/213165475-18b8c6ee-63eb-4e0b-887f-4b09294c18e3.mp4

**Comment by adamearle** [comment]
There seems to still be a problem with this one 

1. Nudges left and not create the keyframe
2. Creating a blank Keyframe out in the wild seems to not be working


https://user-images.githubusercontent.com/16330340/213364238-3fc59e0d-4c7d-47a3-8f9d-0a5b5bb7081a.mp4
