### ISSUE TITLE
Combine  Merge Icons need to be redefined

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#63]
These icons are not  clear enough

**Comment by adamearle** [comment]
**Separate:**
![Seperate selection](https://user-images.githubusercontent.com/16330340/213366997-5abb951a-ad9a-4387-83cb-17974d457d8f.png)

**Combine:**
![Combine With Active Object](https://user-images.githubusercontent.com/16330340/213367018-937f7867-668e-43d5-b609-ef5bb2c15afa.png)

**Comment by SuddenDevelopment** [comment]
replaced
