### ISSUE TITLE
Ctrl + Click Functionality

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#65]
Holding down the Ctrl key = Left action instead of the default action to the right.

1. Add key 
2. Remove key
3. Blank key
4. Duplicate key

**Comment by SuddenDevelopment** [comment]
understood

**Comment by SuddenDevelopment** [comment]
need to know what remove key and duplicate key with ctrl+click

because they currently dont move or push frames

**Comment by SuddenDevelopment** [comment]
test out what;s there, define what's missing please

**Comment by adamearle** [comment]
We need to talk about Blender's negative keyframing ability.


### Remove key
Remove key behaves the same way as add behavior currently.

### Add Key/ Remove key/ Insert Blank key
The behavior is correct except for 2 circumstances
1. when there's no space for a key to move left.
in this instance, Keyframes move right to be able to insert a keyframe to the left of the current keyframe.

The timeline indicator at this point should give the appearance of not moving.

2.  Currently the spaces get closed. I have a few idea on what should happen, but i am curious to hear what you have to say.

**Add Key Demo**
https://user-images.githubusercontent.com/16330340/213921142-c0101083-c1b1-4721-aee0-821870da9008.mp4

**Comment by SuddenDevelopment** [comment]
we decided to leave this as a user thing to figure out when no space is left
