### ISSUE TITLE
Pin Frames

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#67]
This functionality will be exactly the same as the separate button to offer similar behavior to onion skinning.
The only difference will be:
1. on creation Remove Materials and add a fill material with transparency
2. Tag the objects as a pin frame  for deleting pin frame

### Button Operations
1. Click to add pin frame
2. Ctrl + Click to remove all pin frames
3. Alt + Click to remove the current selected pin frame

![Pin Frame](https://user-images.githubusercontent.com/16330340/213368179-264200bd-f78a-4833-a692-2b577dba5075.png)

**Comment by adamearle** [comment]
Let's talk about this.

**Comment by SuddenDevelopment** [comment]
let's reduce to 2 modes for now please = pin and unpin
ctrl = unpin

select as many frames as you want on active object, pin them

ctrl+pin button unpins them for active object

all other combos (easy to think of others) can wait

**Comment by SuddenDevelopment** [comment]
also, we can attempt this one but dont think the details should get in the way of a release

**Comment by SuddenDevelopment** [comment]
it's there, try it out!

**Comment by adamearle** [comment]
I think this works well enough. 
The only one thing is that is that it should remain on the initial object that is being animated and maintain the the current mode
