### ISSUE TITLE
Button size is too big

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#68]

**Comment by adamearle** [comment]
Scaling up behaves better than scaling down. What if we are to start at the smallest resolution? 
Maybe start at Blender's default icon resolution and have the user scale up if they wish too.

![image](https://user-images.githubusercontent.com/16330340/213949784-4be44a0d-9bb9-4699-bdce-ac9af985cb6d.png)

**Comment by adamearle** [comment]
### 32 x 32
[Buttons 32 x32.zip](https://github.com/SuddenDevelopment/StopMotion/files/10476629/Buttons.32.x32.zip)

![Add To Asset Library](https://user-images.githubusercontent.com/16330340/213962912-6bcdfa97-bb95-4831-87eb-0e60f03d3b1b.png)
![Add To Selected Object](https://user-images.githubusercontent.com/16330340/213962914-8ae14cf4-d0d4-413c-a071-25f31e0a4423.png)
![Basic Copy](https://user-images.githubusercontent.com/16330340/213962917-b2d56266-d1a7-4c89-bd20-b1b96321152f.png)
![Basic Cut](https://user-images.githubusercontent.com/16330340/213962919-5c8659fe-7851-4514-84d7-cc9115faf6e9.png)
![Basic Paste](https://user-images.githubusercontent.com/16330340/213962920-ad41cfb5-6753-48de-9ced-57940e71830c.png)
![Combine With Active Object](https://user-images.githubusercontent.com/16330340/213962923-a0910d01-e557-4143-93a7-bcaaad3ab035.png)
![Data Copy](https://user-images.githubusercontent.com/16330340/213962924-8f2307dc-b642-4a90-aaaa-dee8dcb1df29.png)
![Data Cut](https://user-images.githubusercontent.com/16330340/213962926-31814218-7059-4690-afb9-4f6db3451fc1.png)
![Data Paste](https://user-images.githubusercontent.com/16330340/213962927-23eed1d1-a0db-4ac7-b549-e6b0753da278.png)
![Duplicate Object   Keys](https://user-images.githubusercontent.com/16330340/213962928-66d56b4f-d53d-4436-bf9a-d11cd50a8870.png)
![Duplicate Object With Blank Keys](https://user-images.githubusercontent.com/16330340/213962929-06324c1c-e7ed-4023-be3d-fe621b1a6c22.png)
![Duplicate Object With No Keys](https://user-images.githubusercontent.com/16330340/213962931-3f8c9f2e-bc0a-40bf-a53f-300b3d1d640c.png)
![Flip H](https://user-images.githubusercontent.com/16330340/213962933-960e2137-47bb-45b9-a2fc-5392503543a0.png)
![Flip V](https://user-images.githubusercontent.com/16330340/213962934-706583e0-429e-4aeb-9695-9eb368d9619e.png)
![Key Clear](https://user-images.githubusercontent.com/16330340/213962936-b84acedb-f45a-4404-9e88-a05e83cc7498.png)
![Key Copy](https://user-images.githubusercontent.com/16330340/213962937-7eaabcef-9792-4518-8024-974ed0d69682.png)
![Key Cut](https://user-images.githubusercontent.com/16330340/213962938-5b1414c5-81c6-471e-8baa-de57dbb49b48.png)
![Key Duplicate](https://user-images.githubusercontent.com/16330340/213962939-97a1558c-4fa0-4b07-a45c-5b0710e7f903.png)
![Key Insert Blank](https://user-images.githubusercontent.com/16330340/213962941-e13aadfa-daa8-4016-a282-b3edaa25a625.png)
![Key Insert Many Blank](https://user-images.githubusercontent.com/16330340/213962943-c4ceb80d-c8db-4346-835d-99186be724e3.png)
![Key Insert](https://user-images.githubusercontent.com/16330340/213962945-5475b92e-4296-434a-83c8-c88357b9954b.png)
![Key Paste](https://user-images.githubusercontent.com/16330340/213962946-797ed810-7208-42c4-ab20-69ccda06e66b.png)
![Key Remove](https://user-images.githubusercontent.com/16330340/213962947-3b8560fd-a59e-46c1-b0a6-656fa55ce987.png)
![Key Unique Duplicate](https://user-images.githubusercontent.com/16330340/213962949-651371f7-871e-4086-86c7-5be24dc49bc2.png)
![Object Copt](https://user-images.githubusercontent.com/16330340/213962950-f035356e-2517-409b-981b-bbb64e790c0e.png)
![Object Cut](https://user-images.githubusercontent.com/16330340/213962951-fec570d8-4e65-46ab-877d-fce36a787318.png)
![Object Paste](https://user-images.githubusercontent.com/16330340/213962953-3bd8b705-04c6-4311-a325-37c5a3ca1d07.png)
![Onion skin](https://user-images.githubusercontent.com/16330340/213962954-02d2dec8-ed0c-4ba0-979e-31c116980b31.png)
![Pin Frame](https://user-images.githubusercontent.com/16330340/213962956-54f25530-0b39-48ad-86aa-7044533fe0b2.png)
![Preferences](https://user-images.githubusercontent.com/16330340/213962959-11431144-db66-4a57-bdc8-9e8f76cdb38a.png)
![Seperate selection](https://user-images.githubusercontent.com/16330340/213962960-1b296c66-88fc-4a00-85ad-483410f42b49.png)
![Space Add Half Button](https://user-images.githubusercontent.com/16330340/213962962-27f37298-d482-4cd7-bdce-6799d4b48723.png)
![Space Add](https://user-images.githubusercontent.com/16330340/213962967-387c9d66-163c-482f-990f-74b67cfe1962.png)
![Space Non Half Button](https://user-images.githubusercontent.com/16330340/213962969-dd07935d-5b98-4da0-a5ca-22716c4cf603.png)
![Space None](https://user-images.githubusercontent.com/16330340/213962970-aa4eb71f-befb-4291-90f8-141f8ab29430.png)
![Space Remove Half Button](https://user-images.githubusercontent.com/16330340/213962971-92bbac45-6701-47b5-8458-62c5fd4364b0.png)
![Space Remove](https://user-images.githubusercontent.com/16330340/213962973-46337ead-2e1f-4ae7-870b-86f886388c10.png)
![Space Set Half Button](https://user-images.githubusercontent.com/16330340/213962974-4f7e009e-1009-4fe8-93ed-9a3d218b90e6.png)
![Space Set](https://user-images.githubusercontent.com/16330340/213962975-279ab611-9fc9-4bb4-bd2c-22a40725dc42.png)
![UI Switch](https://user-images.githubusercontent.com/16330340/213962976-b95e18b3-62a1-421d-be52-44cfed6a2ac8.png)
![Add Selected To Asset Library](https://user-images.githubusercontent.com/16330340/213962909-2e60af66-5425-4124-83ae-88040b7a5bdf.png)

**Comment by adamearle** [comment]
### 16 x 16
[Buttons 16 x16.zip](https://github.com/SuddenDevelopment/StopMotion/files/10476637/Buttons.16.x16.zip)

**Comment by SuddenDevelopment** [comment]
done, let me know how it looks, re-spacing took some time
