### ISSUE TITLE
Clear Frame

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#72]
### **Clear methods:**
1. Current behavior 
2. If in **edit mode** and parts of the geometry are selected = clear _(delete)_ only selection.

There is no need for ctrl Click on this button I believe so far.

**Comment by SuddenDevelopment** [comment]
if in edit mode:
   delete all selected points on a curve or mesh
if in object mode:
   delete ALL geometry on active_object

**Comment by SuddenDevelopment** [comment]
ready to test

**Comment by adamearle** [comment]
### Object mode:
Click = Delete everything
Ctrl + Click = Nothing? 

### Edit mode:
Click = Delete everything
Ctrl + Click = delete just the selected

**Comment by SuddenDevelopment** [comment]
ready to test
