### ISSUE TITLE
Add Key Need to move right on creation

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#73]

**Comment by SuddenDevelopment** [comment]
please retest we looked together and it looked good

**Comment by adamearle** [comment]
Sometimes working, sometimes not in area like this between keys. right now it's working. lets come back to this one

https://user-images.githubusercontent.com/16330340/214038928-04cea694-be69-4d71-959c-10e48b4b9aaa.mp4

**Comment by SuddenDevelopment** [comment]
currently not actionable, closing. your video looks great, had all 3 states working
