### ISSUE TITLE
Set Spacing

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#76]
Something happened here and I'm not sure what it is

https://user-images.githubusercontent.com/16330340/214038009-e526513a-e18d-4020-b7b7-1a24aaf3568f.mp4

https://user-images.githubusercontent.com/16330340/214038251-58c2abc2-95f5-4b08-b958-ba7b9a6a7334.mp4

**Comment by SuddenDevelopment** [comment]
ready to test
