### ISSUE TITLE
Clear Key

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#77]
Added functionality:
Alt + Click remove/ delete inverted selection

**Comment by adamearle** [comment]
i'm not sure about adding this. I don't think it is difficult to add. But at the same time I want people to learn hotkeys as well.
I can see the benefits of adding this. I am wanting to use it all the time.

**Comment by adamearle** [comment]
Test this one I don't think its set up yet.

**Comment by SuddenDevelopment** [comment]
it works, but I forgot to add it in the n-panel, it's there now

**Comment by adamearle** [comment]
This is not work working for me

- [ ] Click = Clear all
- [ ] Ctrl + Click = Clears Seleceted
- [ ] Alt + Click  = Clears inverted selected

**Comment by SuddenDevelopment** [comment]
yeah I never did an alt version. seamed out of scope / scope creep

**Comment by SuddenDevelopment** [comment]
done
