### ISSUE TITLE
Selection intelligence

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#78]
Have a think about this and shift it to Medium Priority

I can see this kind of intelligence in all object selection types.

Intelligence:
1. Object mode: If no object or vertices are selected **Operation** only on the current frame.
2 Object mode: If objects are selected it pins the objects
3. Edit mode: No selection **Operation** 
4. Edit mode: Selection made **Operation** on selection.

**Comment by SuddenDevelopment** [comment]
This is a lot of confusing stuff vs allowing the user select things and maybe making it easier to select things. a big part of a couple addons I made was making things easier to select within the context of that addon, like select everything with a certain vertex color
