### ISSUE TITLE
Tool Tips

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#79]
- [ ] Consistency: sometimes they're not pop up.
- [x] Faster on popup if possible.
- [x] Let's get the Shortcut key mentioned in the tool Tips.

**Comment by SuddenDevelopment** [comment]
I included all the descriptions for ctrl+ behavior mentioned, is there something else?

**Comment by adamearle** [comment]
All of the information isn't showing up in the Tool Tips. I think the tool tip box is set to the same size for all the tips. 

We can set the aspect ratio to be dynamic. one way be to keep the width the box the same  and the height of the tool tip box increase based on its content.

**Comment by adamearle** [comment]
fix formating

**Comment by adamearle** [comment]
@SuddenDevelopment I may have broken this again

**Comment by SuddenDevelopment** [comment]
I fixed it

**Comment by adamearle** [comment]
Can't see the full description of the tool tip.

**Comment by SuddenDevelopment** [comment]
changed the max lines for tooltip

**Comment by adamearle** [comment]
I have broken this somewhere. Maybe you show me how to search for my mistake?

sorry.

**Comment by SuddenDevelopment** [comment]
no problem, it's easier in VSCode it highlights where the issue is. After we launch, before next release I will move this into a config file json that isn't mixed with code.
