### ISSUE TITLE
Clear Frame

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#80]
Clear frame needs to work in objec t mode and edit mode

**Comment by SuddenDevelopment** [comment]
cannot reproduce issue, but I may have fixed it?

**Comment by adamearle** [comment]
I get this message that comes up

![image](https://user-images.githubusercontent.com/16330340/215369036-d8cd8b0f-2f99-467c-acf1-0778de300fc6.png)

**Comment by adamearle** [comment]
Clear key frame also isn't in the N panel

**Comment by adamearle** [comment]
Something was happening inside of Blender. I'm not sure what this was resetting Blender back to its default settings seems to fix this problem.

i think there maybe something in the other addons that I was using to cause this problem.
