### ISSUE TITLE
Separate Frame: copy transforms

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#86]
Object mode seems to no be working

**Hotkeys**
1. Click = copy out
2. Ctrl + Click = Cut out

**Behavours**
1. Objects mode the operation works with the entire objects and selected keys.
2. Objected select no keyframe selected operation does just the current key.
3. Edit mode no selection nothing happens.
4. Edit mode operation works with just the selection.

**Comment by SuddenDevelopment** [comment]
ready to retest

**Comment by adamearle** [comment]
I think this might be completely broken

**Comment by adamearle** [comment]
Copy & Cut separates and sends the object back to its object 0 default state of 0 for Translation Rotation Scale. This may also be the same for the pin frame.

The object needs to maintain its Position Rotation and scale in space when the object has been animated.

**Comment by SuddenDevelopment** [comment]
ok seeing if I got it right:
Need to get the transforms from the primary / stop motion object at the frame point we are separating
and apply to the separated objects (or pinned frame)

Can I grab the previous keyed position or does it have to capture the estimated tween at that frame?

**Comment by SuddenDevelopment** [comment]
set location, rotation, scale of separated object to where it was in at the current frame

**Comment by SuddenDevelopment** [comment]
transforms now copy to separated objects at frame separated. try it out!

**Comment by adamearle** [comment]
Here are my thoughts on this. the compression of the file is no good.


https://user-images.githubusercontent.com/16330340/216309964-8bd0d21b-6de2-4110-9013-1f4fdefbacdf.mp4

**Comment by SuddenDevelopment** [comment]
this got me way confused. most of the video it seems you are talking about a completely new and significant feature that should be its own ticket and evaluated for next release.

I need to better understand exactly what we need to do with the separate keyframe objects function, remove it reduce it's scope etc. but not completely transform it into something new at this stage

**Comment by adamearle** [comment]
**Hotkeys**
1. Click = Copy out
2. Ctrl + Click = Cut out

Behaviors: Only works with selections. Not keyframe dependent. _(at the moment this depends on keyframes and we need to separate it from that behavior)_

**Object mode:**
1. The operation works with selected objects. Not dependent on keyframes.

**Edit mode:**
2. Works with just the selection.

Keyframes:
3. I think needs to get droped

**Comment by SuddenDevelopment** [comment]
as discussed, old behavior is moving to alt_click

**Comment by SuddenDevelopment** [comment]
cut doesnt make sense in the context of current frame and between / independent of keyframes

**Comment by SuddenDevelopment** [comment]
ready to test

**Comment by SuddenDevelopment** [comment]
eval current frame fcurves for data block (animall)

**Comment by SuddenDevelopment** [comment]
now with datablock keys

**Comment by SuddenDevelopment** [comment]
test again please, a lot has changed

**Comment by adamearle** [comment]
Seems to be working the only thing is: _When in **Edit Mode** and there are selected points they don't copy out._

That's it really.
