### ISSUE TITLE
Combine/ Merge Creates 2 keyframes

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#87]
I'm lost. I think we had this working

**Click** Combine needs to merge with only the current keyframe on.
**Ctrl+Click** Merges into new keyframes.

**Comment by SuddenDevelopment** [comment]
we DID have it working, but the more we change the more we break, which is part of the reason for wanting to delay new features and focus where we can. working on it

**Comment by SuddenDevelopment** [comment]
this is counter intuitive to me, need to discuss.
most of our actions are click = everything selected and ctrl+click is a smaller (more controlled) action.

also I'm niot sure I know what you mean by above descriptions.

**Comment by SuddenDevelopment** [comment]
primary function is "ctrl+j" functionality

ctrl is the old add all the keyframes functionality

**Comment by SuddenDevelopment** [comment]
easily added back in as ctrl

**Comment by adamearle** [comment]
Copy & Cut separates and sends the object back to its object 0 default state of 0 for Translation Rotation Scale. This may also be the same for the pin frame.

The object needs to maintain its Position Rotation and scale in space when the object has been animated.

**Comment by SuddenDevelopment** [comment]
When combining the object in as a frame, remove the old one

**Comment by SuddenDevelopment** [comment]
old one is removed when inserting frame objects, and the 2 key thing is fixed as well

**Comment by adamearle** [comment]
**Click Merge** = Normal Merge works like a charm
**Ctrl + Click Merge** = Multiple keyframe merging isn't respect the objects position rotation and scale
