### ISSUE TITLE
Object animation block stopmotion keys

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#88]
1. Use autokey to keyframe an objecet.
2. The try to keyframe the stopmotion object. Keyframing not working.

https://user-images.githubusercontent.com/16330340/215017266-0ec9dea6-a9ff-43e8-9be8-de0dad45a2d4.mp4

**Comment by SuddenDevelopment** [comment]
LOL yeah that's a huge gotcha, totally fixable

**Comment by SuddenDevelopment** [comment]
should be good now, condition gap found
