### ISSUE TITLE
Remove key

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#89]
Remove  key needs to remove object keyframes as well not just stop motion keyframes

**Comment by SuddenDevelopment** [comment]
done
ctrl + remove will only remove stop motion key

**Comment by adamearle** [comment]
Quickly tested not working on my end holding down ctrl is not removing the stop motion key.

**Comment by SuddenDevelopment** [comment]
ok this is ready again, keep in mind it PULLS frames when it removes the current ones, but the all vs stopmption is better coordinated now

**Comment by adamearle** [comment]
Let's Turn off the Ctrl functionality. It's too confusing for the user I think. Best to keep things simple. Even though I understand it, it feels like an error. 

Sooner or later the user is going to have to get their fingerprints all over the keys. Thats a must

Click removes all keys.

**Comment by SuddenDevelopment** [comment]
ctrl on remove key removed, easily added back again if needed

**Comment by adamearle** [comment]
Here are my thoughts on this. the compression of the file is no good

https://user-images.githubusercontent.com/16330340/216304637-1b286df5-4f3b-4d74-a826-80baa4309267.mp4

**Comment by SuddenDevelopment** [comment]
needs to clear animall keys in data block

**Comment by SuddenDevelopment** [comment]
datablock included

**Comment by adamearle** [comment]
remove stopmotion **ctrl+click functionality**
