### ISSUE TITLE
Assign New StopMotion keys different colors

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#9]
Assigning new StopMotion keys will help the user work out if they are keying correctly between both addons.
Some of the code that is needed to do this may be in Ubisoftshot Shotmanager Addon.
Link to addon: https://github.com/ubisoft/shotmanager
YouTube Link about the addon: https://www.youtube.com/watch?v=8yBjm6ojwe8&t=6196s&ab_channel=SpitfireStoryboards

![image](https://user-images.githubusercontent.com/16330340/198414250-1e5b69ca-83ce-460d-8a95-5471300b939e.png)

**Comment by SuddenDevelopment** [comment]
https://docs.blender.org/api/current/bpy.types.FCurve.html#bpy.types.FCurve.color
