### ISSUE TITLE
Keyframing

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#93]
Let's have a chat about this.

**Some things to think about?**
1. Process of keyframing.
2. Hotkeys.
3. Setting the first key.
4. Storing a default pose for keys.

- [ ] define hotkeys
- [ ] define colors for keys
- [ ] define all the state combinations

**Comment by SuddenDevelopment** [comment]
- hotkeys, just need to be defined.
- need to find the balance of flexibility and automating, doing too much for the user reduces flexibility

- not actionable for launch.

**Comment by SuddenDevelopment** [comment]
color codes by key type?
where does autokey fit in?
use of animAll with it

**Comment by adamearle** [comment]
I think there is something in this  for us to work with
https://user-images.githubusercontent.com/16330340/216306894-01f628d7-4c71-462c-823f-00d0976e49fa.mp4

**Comment by adamearle** [comment]
I think there is something in this for us to work with

https://user-images.githubusercontent.com/16330340/216307074-0797d489-d247-492a-a861-d51dd243fd28.mp4
