### ISSUE TITLE
Frame Objects:  Separate objects out.

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#97]
1.  Serepating objects out works.
2.  Separating selection out in edit mode doesn't work.

We need number 2 on the above list to work as well?

**Comment by SuddenDevelopment** [comment]
Easily done.

**Comment by SuddenDevelopment** [comment]
from edit mode:
if partial object is selected, does the selection get copied or cut?
does it get the object transforms applied from that frame?
it cannot have the mesh transforms because it's partial

**Comment by SuddenDevelopment** [comment]
ready to try out, edit mode separate selected geo that is, can also try the alt+click :)
