### ISSUE TITLE
Duplicate key behaviour

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/StopMotion#98]
When the object is selected and no keys are selected the timeline playhead moves forward.

I think **Duplicate key** might need to work a little more like **Add Key**.
This means being about to insert a duplicate without the key being selected. This means its reading the current zone of the keyframe and adding where the play head is in position. the current behavior is still needed

Chat about it?

### Question about duplicate keys?
1.  To have 2 keyframes or more in different places on the timeline. Means duplicate keyframes will all update at the same time.
             1.1. How can an artist determine at a glance which keys are related to each other?

2.  To help the artist to understand the frame range of what they can be auto-tweening using the AnimAll key. This is for display purposes for keyframe management.
             2.1. Stop motion keys set up zones for vertex data to be tweened.
             2.2. How else can these zones be displayed?

![image](https://user-images.githubusercontent.com/16330340/216748618-d9bd0d64-3361-4acf-8541-4b71d32d4402.png)

3  How should keyframes be added to the timeline.
             3.1. Select the key and then Hotkey.
             3.2. Select the key Button and click.
             3.3.  Reading the current key.

**Comment by adamearle** [comment]
Works Great.

Both keys need to be made purple on creation.

This is what it looks like at the moment. Notice the Blue and Purple key.
![image](https://user-images.githubusercontent.com/16330340/217997212-07be6b09-292d-47b9-950e-3abcf56cffdc.png)

Let's get it to look like this.

![image](https://user-images.githubusercontent.com/16330340/217997492-92a742aa-c995-46a3-97b6-bcf41820abf7.png)

**Comment by SuddenDevelopment** [comment]
done
